name: github/delete-package

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'NuGet package name'
        required: true
      package_version:
        description: 'NuGet package version'
        required: true

jobs:
  delete-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Delete NuGet Package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          PACKAGE_NAME: ${{ inputs.package_name }}
          PACKAGE_VERSION: ${{ inputs.package_version }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            "/orgs/$OWNER/packages/nuget/$PACKAGE_NAME/versions/$PACKAGE_VERSION"
