blank_issues_enabled: false
contact_links:
  - name: Support Forum
    url: https://github.com/DuendeSoftware/community
    about: The place for questions, bug reports, support and feature requests
  - name: Direct Contact
    url: https://duendesoftware.com/contact
    about: Contact us directly
